<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <NoWarn>CS0168,CS1998,BL9993,CS0649,CS0436,0436</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Data\DMdelContext.Custom.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\DMdelContext.Custom.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="6.0.0-preview.4.21253.7" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Radzen.Blazor" Version="4.30.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Syncfusion.Compression.Portable">
      <HintPath>..\..\others\Syncfusion.Compression.Portable.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>..\..\others\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Pdf.Portable">
      <HintPath>..\..\others\Syncfusion.Pdf.Portable.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>